config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "static_pages#homepage"
  resources :users

  resources :dishes

  resources :dishes do
    resources :reviews
  end

  get 'plans' => 'subscriptions#plans'
  get 'choose-meals', :to => 'subscriptions#choose_meals'
  post 'add_to_cart/:dish_id' => 'subscriptions#add_to_cart', :as => 'add_to_cart'
  post 'clear_cart' => 'subscriptions#clear_cart'
  post 'remove_from_cart/:dish_id' => 'subscriptions#remove_from_cart', :as => 'remove_from_cart'
  resource :subscription
  delete '/cancel_subscription' => 'subscriptions#destroy'
  get 'on-the-menu' => 'menus#menu', :as => :menu_selections
end

app/views/shared/_alert_messages.html.erb
<% unless flash.empty? %>

  <script type="text/javascript">

    <% flash.each do |f| %>

      <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>

      toastr['<%= type %>']('<%= f[1] %>', '', {"closeButton": false, "debug": false, "positionClass": "toast-bottom-full-width", "onclick": null, "showDuration": "300", "hideDuration": "1000", "timeOut": "5000", "extendedTimeOut": "1000", "showEasing": "swing", "hideEasing": "linear", "showMethod": "fadeIn", "hideMethod": "fadeOut" });

    <% end %>

  </script>

<% end %>

app/views/shared/_checkout_header.html.erb
<header style="margin-bottom: 5rem;">
 <!-- Fixed navbar -->
 <nav class="navbar navbar-expand-md fixed-top" style="background-color: #fff;">
    <div class="container">
     <div class="topbar-brand">
       <%= link_to root_path do %>
         <%= image_tag('logo.png', height: 60, class: 'text-center', alt: "Slice a Dish") %>
       <% end %>
     </div>
     <div class=" d-none d-sm-block">
       <ul class="mx-auto nav nav-process nav-process-in-circles" style="padding-top: 0.3rem; padding-bottom: 0rem; margin-top: -1.1rem;">
         <li class="nav-item processing">
           <a class="nav-link fs-16">1</a>
           <span class="fs-14 fw-300">Welcome</span>
         </li>
         <li class="nav-item processing">
           <a class="nav-link fs-16">2</a>
           <span class="fs-14 fw-300">Pick Plan</span>
         </li>
         <li class="nav-item complete">
           <a class="nav-link fs-16">3</a>
           <span class="fs-14 fw-300">Checkout</span>
         </li>
       </ul>
     </div>
     <div class=" d-sm-none">
       <ul class="mx-auto nav nav-process nav-process-in-circles" style="padding-top: 0.3rem; padding-bottom: 0rem; margin-top: -1.1rem;">
         <li class="nav-item processing">
           <a class="nav-link fs-16">1</a>
         </li>
         <li class="nav-item processing">
           <a class="nav-link fs-16">2</a>
         </li>
         <li class="nav-item complete">
           <a class="nav-link fs-16">3</a>
         </li>
       </ul>
     </div>
   </div>
 </nav>
</header>

app/views/shared/_choose_meals_header.html.erb
<header style="margin-bottom: 5rem;">
  <!-- Fixed navbar -->
  <nav class="navbar navbar-expand-md fixed-top" style="background-color: #fff;">
    <div class="container">
      <div class="topbar-brand">
        <%= link_to root_path do %>
          <%= image_tag('logo.png', height: 60, class: 'text-center', alt: "Slice a Dish") %>
        <% end %>
      </div>
      <div class=" d-none d-sm-block">
        <ul class="mx-auto nav nav-process nav-process-in-circles" style="padding-top: 0.3rem; padding-bottom: 0rem; margin-top: -1.1rem;">
          <li class="nav-item processing">
            <a class="nav-link fs-16">1</a>
            <span class="fs-14 fw-300">Welcome</span>
          </li>
          <li class="nav-item processing">
            <a class="nav-link fs-16">2</a>
            <span class="fs-14 fw-300">Pick Plan</span>
          </li>
          <li class="nav-item complete">
            <a class="nav-link fs-16">3</a>
            <span class="fs-14 fw-300">Pick Meals</span>
          </li>
          <li class="nav-item processing">
            <a class="nav-link fs-16">3</a>
            <span class="fs-14 fw-300">Checkout</span>
          </li>
        </ul>
      </div>
      <div class=" d-sm-none">
        <ul class="mx-auto nav nav-process nav-process-in-circles" style="padding-top: 0.3rem; padding-bottom: 0rem; margin-top: -1.1rem;">
          <li class="nav-item processing">
            <a class="nav-link fs-16">1</a>
          </li>
          <li class="nav-item complete">
            <a class="nav-link fs-16">2</a>
          </li>
          <li class="nav-item processing">
            <a class="nav-link fs-16">3</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/shared/_footer.html.erb
<footer class="curated-footer">
  <div class="row" style="margin-top: 10px; margin-bottom: 10px;">

    <div class="col-6 col-md-3 col-lg-3 text-center text-lg-center">
      <ul class="nav flex-column">
        <li class="nav-item">
          <a class="nav-link" href="https://www.facebook.com/sliceadish"><i class="fa fa-facebook" aria-hidden="true"></i> Facebook</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="https://www.twitter.com/"><i class="fa fa-twitter" aria-hidden="true"></i> Twitter</a>
        </li>
      </ul>
    </div>
  </div>
  
<hr>
  <div class="row">
    <div class="col-md-6 text-center aligncenter">
      <p class="nav-link">Copyright © 2020 <a href="https://slicadish.com">Slice a Dish</a>. All rights reserved.</p>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<!-- Fixed navbar (Start) -->
<header style="margin-bottom: 5rem;">
  <nav class="navbar navbar-expand-md fixed-top" style="background-color: #fff;">
  <div class="container">
    <%= link_to root_path do %>
      <%= image_tag('logo.png', height: 60, alt: "Slice a Dish") %>
    <% end %>
<!-- Mobile Responsive navbar button that only appears in mobile screen (Start) -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
<!-- Mobile Responsive navbar button that only appears in mobile screen (End) -->
    <div class="collapse navbar-collapse" id="navbarCollapse">
<!-- Navbar mid buttons (Start) -->
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to 'On The Menu', menu_selections_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Plans', plans_path , class: 'nav-link' %>
          </li>
        </ul>
<!-- Navbar mid buttons (End) -->
<!-- Navbar right buttons (Start) -->

        <ul class="nav nav-pills float-right">

        <% if user_signed_in? %>

          <div class="dropdown show">
            <a class="btn btn-white dropdown-toggle" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Welcome, <%= current_user.first_name %>
            </a>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
              <%= link_to "Settings", edit_user_registration_path, class: 'dropdown-item' %>
              <%= link_to "Support Center", edit_user_registration_path, class: 'dropdown-item' %>
              <div class="dropdown-divider"></div>
              <%= link_to destroy_user_session_url, :method => :delete, class: "dropdown-item" do %>Sign out<% end %>
            </div>
          </div>

        <% else %>

          <li class="nav-item">
            <%= link_to "Log In", new_user_session_path, class: 'nav-link' %>
          </li>

          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary' %>
          </li>

        <% end %>

        </ul>

<!-- Navbar right buttons (End) -->
    </div>
  </div>
  </nav>
</header>
<!-- Fixed navbar (End) -->

app/views/shared/_plans_header.html.erb
<header style="margin-bottom: 5rem;">
  <!-- Fixed navbar -->
  <nav class="navbar navbar-expand-md fixed-top" style="background-color: #fff;">
    <div class="container">
      <div class="topbar-brand">
        <%= link_to root_path do %>
          <%= image_tag('logo.png', height: 60, class: 'text-center', alt: "Slice a Dish") %>
        <% end %>
      </div>
      <div class=" d-none d-sm-block">
        <ul class="mx-auto nav nav-process nav-process-in-circles" style="padding-top: 0.3rem; padding-bottom: 0rem; margin-top: -1.1rem;">
          <li class="nav-item processing">
            <a class="nav-link fs-16">1</a>
            <span class="fs-14 fw-300">Welcome</span>
          </li>
          <li class="nav-item complete">
            <a class="nav-link fs-16">2</a>
            <span class="fs-14 fw-300">Pick Plan</span>
          </li>
          <li class="nav-item processing">
            <a class="nav-link fs-16">3</a>
            <span class="fs-14 fw-300">Pick Meals</span>
          </li>
          <li class="nav-item processing">
            <a class="nav-link fs-16">3</a>
            <span class="fs-14 fw-300">Checkout</span>
          </li>
        </ul>
      </div>
      <div class=" d-sm-none">
        <ul class="mx-auto nav nav-process nav-process-in-circles" style="padding-top: 0.3rem; padding-bottom: 0rem; margin-top: -1.1rem;">
          <li class="nav-item processing">
            <a class="nav-link fs-16">1</a>
          </li>
          <li class="nav-item complete">
            <a class="nav-link fs-16">2</a>
          </li>
          <li class="nav-item processing">
            <a class="nav-link fs-16">3</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/shared/_pricing_header.html.erb
<header style="margin-bottom: 5rem;">
  <!-- Fixed navbar -->
  <nav class="navbar navbar-expand-md fixed-top" style="background-color: #fff;">
    <div class="container">
      <div class="topbar-brand">
        <%= link_to root_path do %>
          <%= image_tag('logo.png', height: 60, class: 'text-center', alt: "Slice a Dish") %>
        <% end %>
      </div>
      <div class=" d-none d-sm-block">
        <ul class="mx-auto nav nav-process nav-process-in-circles" style="padding-top: 0.3rem; padding-bottom: 0rem; margin-top: -1.1rem;">
          <li class="nav-item processing">
            <a class="nav-link fs-16">1</a>
            <span class="fs-14 fw-300">Welcome</span>
          </li>
          <li class="nav-item complete">
            <a class="nav-link fs-16">2</a>
            <span class="fs-14 fw-300">Pick Plan</span>
          </li>
          <li class="nav-item processing">
            <a class="nav-link fs-16">3</a>
            <span class="fs-14 fw-300">Checkout</span>
          </li>
        </ul>
      </div>
      <div class=" d-sm-none">
        <ul class="mx-auto nav nav-process nav-process-in-circles" style="padding-top: 0.3rem; padding-bottom: 0rem; margin-top: -1.1rem;">
          <li class="nav-item processing">
            <a class="nav-link fs-16">1</a>
          </li>
          <li class="nav-item complete">
            <a class="nav-link fs-16">2</a>
          </li>
          <li class="nav-item processing">
            <a class="nav-link fs-16">3</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>