config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "static_pages#homepage"
  resources :users

  resources :dishes

  resources :dishes do
    resources :reviews
  end

  get 'plans' => 'subscriptions#plans'
  get 'choose-meals', :to => 'subscriptions#choose_meals'
  post 'add_to_cart/:dish_id' => 'subscriptions#add_to_cart', :as => 'add_to_cart'
  post 'clear_cart' => 'subscriptions#clear_cart'
  post 'remove_from_cart/:dish_id' => 'subscriptions#remove_from_cart', :as => 'remove_from_cart'
  resource :subscription
  delete '/cancel_subscription' => 'subscriptions#destroy'
  get 'on-the-menu' => 'menus#menu', :as => :menu_selections
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
end

app/controllers/subscriptions_controller.rb
require 'date'

class SubscriptionsController < ApplicationController
#as usual we want to have only authenticated users access our subscription actions
  before_action :authenticate_user!
  @@cart = Hash.new(0)
  @@plan
  @@plan_details
  def plans
    render layout: "plans"
  end
  def new
    puts "in new"
    puts params
    @amount = @@plan_details[0]
    @plan_name = @@plan_details[1]
    @user = User.new
    @taxrate = 0.065
    render layout: "checkout"
  end
  def create
    customer =  if current_user.subscription.stripe_user_id?
                  Stripe::Customer.retrieve(current_user.subscription.stripe_user_id)
                else
                  Stripe::Customer.create(
                    :email => current_user.email,
                    :source => params[:stripeToken]
                  )
                end
    if current_user.subscription.active
      flash[:error] = 'Already a subscriber!'
      redirect_to root_path and return
    end
    wa_taxrate= Stripe::TaxRate.retrieve(
                'txr_1GKiGHGNXNhAWgyjqzbjYHDw',
                )
    current_subscriptions = customer.subscriptions
    puts current_subscriptions
    subscription = customer.subscriptions.create(
      plan: @@plan,
      billing_cycle_anchor: get_subscription_starttime(),
      prorate: 'false',
      tax_percent: wa_taxrate.percentage
    )
    mealCount = @@plan_details[2]
    current_user.subscription.stripe_user_id = customer.id
    current_user.subscription.active = true
    current_user.subscription.meal_count = mealCount
    current_user.subscription.save
    options = {
      stripe_user_id: customer.id,
      stripe_subscription_id: subscription.id,
      plan: @@plan
    }
    flash[:notice] = 'Successfully Subcribed!'
    redirect_to root_path
  end
  def choose_meals
    @@plan = params[:plan]
    @@cart ||= Hash.new(0)
    @cart = @@cart
    # @amount = params[:amount]
    begin
      @@plan_details = get_plan_details(params[:plan])
    rescue
      flash[:notice] = 'Not a valid plan.'
      redirect_to(:plans) and return
    end
    total = @@cart.inject(0) { |sum, tuple| sum += tuple[1] } 
    if total > @@plan_details[2]
      @@cart.clear()
    end
    # menu to display
    @menu = Menu.where(end_date: Date.today..1.week.from_now)
    #@@cart.clear
    puts "Current cart #{@@cart}"
    render layout: "choose_meals"
  end
  def add_to_cart
    puts params[:dish_id]
    total = @@cart.inject(0) { |sum, tuple| sum += tuple[1] } 
    if total >= @@plan_details[2]
      flash[:notice] = 'Only ' + @@plan_details[2].to_s + ' meals allowed in cart.'
      redirect_back fallback_location: root_path
      return
    end
    dish_id = params[:dish_id]
    @@cart[Dish.find(dish_id)] += 1
    #@@cart.push(Dish.find(dish_id), 1)
    puts @@cart
    puts "total #{total + 1}"
    redirect_back fallback_location: root_path
  end
  def clear_cart
    @@cart.clear
    redirect_back fallback_location: root_path
  end
  def remove_from_cart
     puts "Current cart #{@@cart}"
     dish = Dish.find(params[:dish_id])
     if !@@cart.key?(dish)
      flash[:error] = 'Dish not in cart'
      redirect_back fallback_location: root_path and return
     end
     @@cart[dish] -=1
     if @@cart[dish] == 0
      @@cart.delete(dish)
     end
     puts "Current cart #{@@cart}"
    redirect_back fallback_location: root_path
  end
  def update
    @plan = params[:plan]
  end
  def destroy
    customer = Stripe::Customer.retrieve(current_user.subscription.stripe_user_id)
    subscriptions = customer.subscriptions
    subscriptions.each do |sub|
      sub.delete
    end
    # subscription = Stripe::Subscription.retrieve(current_user.stripe_subscription_id)
    # subscription.delete(:at_period_end => true)
    #subscription.delete
    # current_user.update(stripe_subscription_id: nil, cc_last4: nil, cc_exp_month: nil, cc_exp_year: nil, cc_type: nil)
    @plan = params[:plan]
    current_user.subscription.meal_count = nil
    current_user.subscription.active = false
    current_user.subscription.save
    user = current_user
    redirect_to root_path, notice: "Your subscription has been canceled."
  end
  private
    def get_subscription_starttime
      date  = Date.parse("Thursday")
      delta = date > Date.today ? 0 : 7
      newdate = date + delta
      return newdate.to_time.to_i
    end
    def get_plan_details(pln)
      case pln
        when nil  # current_user != nil, skip condition
          raise "This is an exception"
        when "four"  # current_user != current_user.is_admin?, skip condition
          return 59.99, "Four meals", 4 #amount, plan details, count
        when "nine"  # and so on
          return 69.99, "Nine meals", 9
        else
          raise "This is an exception"
        end
    end

end

app/views/subscriptions/choose_meals.html.erb
  <div class="header" style="background-image: url(assets/healthy.jpg);">
    <div class="container" style="padding-top: 4rem; padding-bottom: 4rem;">
      <h1 class="text-white text-center">Dishes for the week of <%= @menu.first.end_date.to_formatted_s(:long_ordinal) %></h1>
    </div>
  </div>

  <div class="py-5 bg-light">
    <div class="container">
      <div class="row">

      <% @menu.first.dishes.each do |dish| %>
          <div class="mx-auto col-12 col-sm-8 col-md-6 col-lg-6 col-xl-4">
            <div class="card mb-4 box-shadow" style="height: auto;">
              <% if dish.image_data.blank? %>
                <%= image_tag('logo.png', alt: "BlueFoodie", class: "card-img-top" ) %>
              <% else %>
                <%= link_to dish do %>
                  <%= image_tag dish.image_url(:original), height: '240', width: 'auto', alt: "BlueFoodie image", class: "card-img-top d-none d-sm-block" %>
                  <%# image_tag dish.image_url(:original), height: 'auto', width: 'auto', alt: "BlueFoodie image", class: "card-img-top d-block d-sm-none" %>
                <% end %>
              <% end %>
              <div class="card-body">
                <h6 class="card-text"><%= dish.title %></h6>
                <small><%= dish.description %></small>
                <%= button_to "+", :action => "add_to_cart" , :method => :post , :dish_id => dish.id %>
                <%= button_to "-", :action => "remove_from_cart" , :method => :post , :dish_id=> dish.id %>
              </div>
            </div>
          </div>
      <% end %>

      <div class="cart-layout">
        <p> Choose your meals </p>
        <%= button_to "Clear", :action => "clear_cart" , :method => :post%>
        <table id="line_items">
          <tr>
            <th>Dish</th>
            <th>Qty</th>
          </tr>

          <% @cart.each do |key, value|%>
            <tr class="<%= cycle :odd, :even %>">
              <td><%=h key.title %></td>
              <td><%=h value%></td>
            </tr>
          <% end %>
        </table>
        <%= link_to 'Checkout', new_subscription_path(:plan => params[:plan]), class: "btn btn-secondary btn-info btn-block" %> <br/>
        </div>
      </div>
    </div>
  </div>
</div>

      </div>
      </div>
    </div>
  </div>

app/views/subscriptions/new.html.erb
<div class="container py-5">
<!-- Checkout header -->
  <div class="text-center">
    <h2>Checkout</h2>
    <p class="lead">Your delivery and payment information</p>
  </div>
  <!-- Payment Form -->
  <%= form_for subscription_path, url: { action: 'create', method: 'post' }, html: { id: 'payment-form' } do |form| %>
    <span class="payment-errors"></span>
    <br>
    <noscript>JavaScript is not enabled and is required for this form. First enable it in your web browser settings.</noscript>
   <!-- Hidden Field Tags -->
    <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
    <%= hidden_field_tag :plan, @plan %>
    <%= hidden_field_tag :amount, @amount %>
    <div class="row">
      <!-- Order Description -->
      <div class="col-md-4 order-md-2 mb-4">
        <h4 class="d-flex justify-content-between align-items-center mb-3">
          <span class="text-muted">Your order</span>
        </h4>
        <ul class="list-group mb-3">
          <li class="list-group-item d-flex justify-content-between lh-condensed">
            <div>
              <h6 class="my-0"><%= @plan_name.capitalize %> Plan</h6>
              <small class="text-muted">
                Aliquam at lectus turpis. Sed interdum lorem vel ipsum commodo elementum. Cras ac tortor sem. Sed eu ante elit.
              </small>
            </div>
            <span class="text-muted"></span>
          </li>
          <li class="list-group-item d-flex justify-content-between lh-condensed">
            <div>
              <h6 class="my-0">Subscription</h6>
              <small class="text-muted">Weekly</small>
            </div>
            <span class="text-muted">$<%= @amount %></span>
          </li>
          <li class="list-group-item d-flex justify-content-between lh-condensed">
            <div>
              <h6 class="my-0">Tax</h6>
            </div>
            <% @totalAmount =  (('%.2f' % (@taxrate * @amount.to_f)).to_f + @amount.to_f).to_s%>
            <span class="text-muted"><%= "$" + ('%.2f' % (@taxrate * @amount.to_f)).to_s %></span>
          </li>
          <li class="list-group-item d-flex justify-content-between lh-condensed">
            <div>
              <h6 class="my-0">Shipping</h6>
            </div>
              <span class="text-muted">FREE</span>
          </li>
          <li class="list-group-item d-flex justify-content-between">
            <span>Total (USD)</span>
            <strong>$<%= '%.2f' % @totalAmount %></strong>
          </li>
        </ul>
      </div>
      <!-- Delivery Information (User) -->
      <%= form.fields_for current_user do |u| %>
        <div class="col-md-8 order-md-1">
          <h4 class="mb-3">Delivery address</h4>
            <div class="row">
              <div class="col-md-6 mb-3">
                <label>First name</label>
                  <%= u.text_field :first_name, :id => "first_name", :class => "form-control", :placeholder => "First Name", required: true, autofocus: true %>
              </div>
              <div class="col-md-6 mb-3">
                <label for="lastName">Last name</label>
                <%= u.text_field :last_name, :id => "last_name", :class => "form-control", :placeholder => "Last Name", required: true, autofocus: true %>
              </div>
            </div>
            <div class="mb-3">
              <label for="address">Address</label>
              <%= u.text_field :address1, :id => "address1", :class => "form-control", :placeholder => "Address", required: true, autofocus: true %>
            </div>
            <div class="mb-3">
              <label for="address2">Address 2 <span class="text-muted">(Optional)</span></label>
              <%= u.text_field :address2, :id => "address2", :class => "form-control", :placeholder => "Apartment or Suite Number", autofocus: true %>
            </div>
            <div class="row">
              <div class="col-md-5 mb-3">
                <label for="country">Country</label>
                <%= u.select(:country, ['United States'], {}, { :class => 'custom-select d-block w-100' }) %>
              </div>
              <div class="col-md-4 mb-3">
                <label for="state">State</label>
                <%= u.select(:state, ['Washington'], {}, { :class => 'custom-select d-block w-100' }) %>
              </div>
              <div class="col-md-3 mb-3">
                <label for="zip">Zip</label>
                <%= u.text_field :zip, :id => "zip", :class => "form-control", :placeholder => "Zip Code", :pattern=>"[0-9]{5}",required: true, autofocus: true %>
              </div>
            </div>
      <% end %>
      <hr class="mb-4">
      <!-- Payment (Stripe) -->
      <h4 class="mb-3">Payment</h4>
        <div class="d-block my-3">
          <div class="form-row">
            <label for="card-element">
              Credit or debit card
            </label>
            <div id="card-element" class="form-control">
              <!-- a Stripe Element will be inserted here. -->
            </div>
            <!-- Used to display form errors -->
            <div id="card-errors" role="alert"></div>
          </div>
        <br>
        <hr class="mb-4">
        <button class="btn btn-primary btn-lg btn-block" type="submit">Subscribe</button>
        </div>
    </div>
  <% end %>
</div>

app/views/subscriptions/plans.html.erb
<!-- Header -->
 <div class="header" style="background-image: url(assets/healthy.jpg); background-size: 100%;">
   <div class="container" style="padding-top: 4rem; padding-bottom: 4rem;">
     <h1 class="text-white text-center">Pricing Plans</h1>
   </div>
 </div>
<!-- Pick Your Plan -->
 <div class="plans-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
   <h1 class="display-4">Pick Your Plan</h1>
   <p class="lead">Pick your perfect plan, or whatever plan you want.</p>
 </div>
<!-- Plans -->
 <div class="container">
   <div class="row">
     <div class="mx-auto col-12 col-md-8 col-lg-6 col-xl-6">
       <div class="card mb-4 box-shadow" style="height: auto;">
         <div class="card-header">
           <h4 class="my-0 text-center font-weight-normal">4 meal plan</h4>
         </div>
         <%= image_tag('healthy.jpeg', height: 320, class: "card-img-top" ) %>
         <div class="card-body mx-auto">
           <h1 class="card-title pricing-card-title">$59.99 <small class="text-muted">/ week</small></h1>
           <ul class="list-unstyled mt-3 mb-4">
             <li class="text-center">3 meals per week</li>
             <li class="text-center">Just $9.99 per person</li>
             <li class="text-center">No Commitment</li>
             <li class="text-center">Free Shipping</li>
           </ul>
           <%# TODO FIX THIS %>
           <%= link_to 'Choose', choose_meals_path(:plan => 'four'), class: "btn btn-secondary btn-info btn-block" %> <br/>
         </div>
       </div>
   </div>
     <div class="mx-auto col-12 col-md-8 col-lg-6 col-xl-6">
       <div class="card mb-4 box-shadow" style="height: auto;ß">
         <div class="card-header">
           <h4 class="my-0 text-center font-weight-normal">9 meal plan</h4>
         </div>
         <%= image_tag('healthy.jpeg', height: 320, class: "card-img-top" ) %>
         <div class="card-body mx-auto">
           <h1 class="card-title pricing-card-title">$79.99 <small class="text-muted">/ week</small></h1>
           <ul class="list-unstyled mt-3 mb-4">
             <li class="text-center">4 meals per week</li>
             <li class="text-center">Just $9.99 per person</li>
             <li class="text-center">No Commitment</li>
             <li class="text-center">Free Shipping</li>
           </ul>
           <%= link_to 'Choose', choose_meals_path(:plan => 'nine'), class: "btn btn-secondary btn-info btn-block" %> <br/>
         </div>
       </div>
     </div>
   </div>
 </div>

app/views/subscriptions/pricing.html.erb
<!-- Header -->
 <div class="header" style="background-image: url(assets/healthy.jpg); background-size: 100%;">
   <div class="container" style="padding-top: 4rem; padding-bottom: 4rem;">
     <h1 class="text-white text-center">Pricing Plans</h1>
   </div>
 </div>
<!-- Pick Your Plan -->
 <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
   <h1 class="display-4">Pick Your Plan</h1>
   <p class="lead">Pick your perfect plan, or whatever plan you want.</p>
 </div>
<!-- Pricing Plans -->
 <div class="container">
   <div class="row">
     <div class="mx-auto col-12 col-md-8 col-lg-6 col-xl-6">
       <div class="card mb-4 box-shadow" style="height: auto;">
         <div class="card-header">
           <h4 class="my-0 text-center font-weight-normal">4 meal plan</h4>
         </div>
         <%= image_tag('healthy.jpeg', height: 320, class: "card-img-top" ) %>
         <div class="card-body mx-auto">
           <h1 class="card-title pricing-card-title">$59.99 <small class="text-muted">/ week</small></h1>
           <ul class="list-unstyled mt-3 mb-4">
             <li class="text-center">3 meals per week</li>
             <li class="text-center">Just $9.99 per person</li>
             <li class="text-center">No Commitment</li>
             <li class="text-center">Free Shipping</li>
           </ul>
           <%# TODO FIX THIS %>
           <%= link_to 'Get started', new_subscription_path(:plan => 'four'), class: "btn btn-secondary btn-info btn-block" %> <br/>
         </div>
       </div>
   </div>
     <div class="mx-auto col-12 col-md-8 col-lg-6 col-xl-6">
       <div class="card mb-4 box-shadow" style="height: auto;ß">
         <div class="card-header">
           <h4 class="my-0 text-center font-weight-normal">9 meal plan</h4>
         </div>
         <%= image_tag('healthy.jpeg', height: 320, class: "card-img-top" ) %>
         <div class="card-body mx-auto">
           <h1 class="card-title pricing-card-title">$79.99 <small class="text-muted">/ week</small></h1>
           <ul class="list-unstyled mt-3 mb-4">
             <li class="text-center">4 meals per week</li>
             <li class="text-center">Just $9.99 per person</li>
             <li class="text-center">No Commitment</li>
             <li class="text-center">Free Shipping</li>
           </ul>
           <%= link_to 'Get started', new_subscription_path(:plan => 'nine', :amount => '79.99'), class: "btn btn-secondary btn-info btn-block" %> <br/>
         </div>
       </div>
     </div>
   </div>
 </div>